// Copyright 2020 Metropolitan Transportation Authority
//
// Mercury extensions for the GTFS-realtime protocol.
//
// Source: https://github.com/OneBusAway/onebusaway-gtfs-realtime-api/blob/master/src/main/proto/com/google/transit/realtime/gtfs-realtime-service-status.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/us-ny-mta-alerts-extension.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MercuryEntitySelector_Priority int32

const (
	MercuryEntitySelector_PRIORITY_NO_SCHEDULED_SERVICE     MercuryEntitySelector_Priority = 1
	MercuryEntitySelector_PRIORITY_NO_MIDDAY_SERVICE        MercuryEntitySelector_Priority = 2
	MercuryEntitySelector_PRIORITY_NO_OVERNIGHT_SERVICE     MercuryEntitySelector_Priority = 3
	MercuryEntitySelector_PRIORITY_NO_WEEKEND_SERVICE       MercuryEntitySelector_Priority = 4
	MercuryEntitySelector_PRIORITY_WEEKDAY_SCHEDULE         MercuryEntitySelector_Priority = 5
	MercuryEntitySelector_PRIORITY_WEEKEND_SCHEDULE         MercuryEntitySelector_Priority = 6
	MercuryEntitySelector_PRIORITY_SATURDAY_SCHEDULE        MercuryEntitySelector_Priority = 7
	MercuryEntitySelector_PRIORITY_SUNDAY_SCHEDULE          MercuryEntitySelector_Priority = 8
	MercuryEntitySelector_PRIORITY_EXTRA_SERVICE            MercuryEntitySelector_Priority = 9
	MercuryEntitySelector_PRIORITY_SPECIAL_SCHEDULE         MercuryEntitySelector_Priority = 10
	MercuryEntitySelector_PRIORITY_STATION_NOTICE           MercuryEntitySelector_Priority = 11
	MercuryEntitySelector_PRIORITY_SPECIAL_EVENT            MercuryEntitySelector_Priority = 12
	MercuryEntitySelector_PRIORITY_PLANNED_BOARDING_CHANGE  MercuryEntitySelector_Priority = 13
	MercuryEntitySelector_PRIORITY_BOARDING_CHANGE          MercuryEntitySelector_Priority = 14
	MercuryEntitySelector_PRIORITY_REDUCED_SERVICE          MercuryEntitySelector_Priority = 15
	MercuryEntitySelector_PRIORITY_PLANNED_WORK             MercuryEntitySelector_Priority = 16
	MercuryEntitySelector_PRIORITY_PLANNED_STATIONS_SKIPPED MercuryEntitySelector_Priority = 17
	MercuryEntitySelector_PRIORITY_PLANNED_EXPRESS_TO_LOCAL MercuryEntitySelector_Priority = 18
	MercuryEntitySelector_PRIORITY_SLOW_SPEEDS              MercuryEntitySelector_Priority = 19
	MercuryEntitySelector_PRIORITY_EXPECT_DELAYS            MercuryEntitySelector_Priority = 20
	MercuryEntitySelector_PRIORITY_PLANNED_LOCAL_TO_EXPRESS MercuryEntitySelector_Priority = 21
	MercuryEntitySelector_PRIORITY_PLANNED_BUSES_DETOURED   MercuryEntitySelector_Priority = 22
	MercuryEntitySelector_PRIORITY_PLANNED_TRAINS_REROUTED  MercuryEntitySelector_Priority = 23
	MercuryEntitySelector_PRIORITY_PLANNED_SUBSTITUTE_BUSES MercuryEntitySelector_Priority = 24
	MercuryEntitySelector_PRIORITY_PLANNED_PART_SUSPENDED   MercuryEntitySelector_Priority = 25
	MercuryEntitySelector_PRIORITY_PLANNED_MULTIPLE_CHANGES MercuryEntitySelector_Priority = 26
	MercuryEntitySelector_PRIORITY_SOME_DELAYS              MercuryEntitySelector_Priority = 27
	MercuryEntitySelector_PRIORITY_STATIONS_SKIPPED         MercuryEntitySelector_Priority = 28
	MercuryEntitySelector_PRIORITY_EXPRESS_TO_LOCAL         MercuryEntitySelector_Priority = 29
	MercuryEntitySelector_PRIORITY_DELAYS                   MercuryEntitySelector_Priority = 30
	MercuryEntitySelector_PRIORITY_SOME_REROUTES            MercuryEntitySelector_Priority = 31
	MercuryEntitySelector_PRIORITY_LOCAL_TO_EXPRESS         MercuryEntitySelector_Priority = 32
	MercuryEntitySelector_PRIORITY_BUSES_DETOURED           MercuryEntitySelector_Priority = 33
	MercuryEntitySelector_PRIORITY_SERVICE_CHANGE           MercuryEntitySelector_Priority = 34
	MercuryEntitySelector_PRIORITY_TRAINS_REROUTED          MercuryEntitySelector_Priority = 35
	MercuryEntitySelector_PRIORITY_SUBSTITUTE_BUSES         MercuryEntitySelector_Priority = 36
	MercuryEntitySelector_PRIORITY_PART_SUSPENDED           MercuryEntitySelector_Priority = 37
	MercuryEntitySelector_PRIORITY_MULTIPLE_CHANGES         MercuryEntitySelector_Priority = 38
	MercuryEntitySelector_PRIORITY_PLANNED_SUSPENDED        MercuryEntitySelector_Priority = 39
	MercuryEntitySelector_PRIORITY_SUSPENDED                MercuryEntitySelector_Priority = 40
)

// Enum value maps for MercuryEntitySelector_Priority.
var (
	MercuryEntitySelector_Priority_name = map[int32]string{
		1:  "PRIORITY_NO_SCHEDULED_SERVICE",
		2:  "PRIORITY_NO_MIDDAY_SERVICE",
		3:  "PRIORITY_NO_OVERNIGHT_SERVICE",
		4:  "PRIORITY_NO_WEEKEND_SERVICE",
		5:  "PRIORITY_WEEKDAY_SCHEDULE",
		6:  "PRIORITY_WEEKEND_SCHEDULE",
		7:  "PRIORITY_SATURDAY_SCHEDULE",
		8:  "PRIORITY_SUNDAY_SCHEDULE",
		9:  "PRIORITY_EXTRA_SERVICE",
		10: "PRIORITY_SPECIAL_SCHEDULE",
		11: "PRIORITY_STATION_NOTICE",
		12: "PRIORITY_SPECIAL_EVENT",
		13: "PRIORITY_PLANNED_BOARDING_CHANGE",
		14: "PRIORITY_BOARDING_CHANGE",
		15: "PRIORITY_REDUCED_SERVICE",
		16: "PRIORITY_PLANNED_WORK",
		17: "PRIORITY_PLANNED_STATIONS_SKIPPED",
		18: "PRIORITY_PLANNED_EXPRESS_TO_LOCAL",
		19: "PRIORITY_SLOW_SPEEDS",
		20: "PRIORITY_EXPECT_DELAYS",
		21: "PRIORITY_PLANNED_LOCAL_TO_EXPRESS",
		22: "PRIORITY_PLANNED_BUSES_DETOURED",
		23: "PRIORITY_PLANNED_TRAINS_REROUTED",
		24: "PRIORITY_PLANNED_SUBSTITUTE_BUSES",
		25: "PRIORITY_PLANNED_PART_SUSPENDED",
		26: "PRIORITY_PLANNED_MULTIPLE_CHANGES",
		27: "PRIORITY_SOME_DELAYS",
		28: "PRIORITY_STATIONS_SKIPPED",
		29: "PRIORITY_EXPRESS_TO_LOCAL",
		30: "PRIORITY_DELAYS",
		31: "PRIORITY_SOME_REROUTES",
		32: "PRIORITY_LOCAL_TO_EXPRESS",
		33: "PRIORITY_BUSES_DETOURED",
		34: "PRIORITY_SERVICE_CHANGE",
		35: "PRIORITY_TRAINS_REROUTED",
		36: "PRIORITY_SUBSTITUTE_BUSES",
		37: "PRIORITY_PART_SUSPENDED",
		38: "PRIORITY_MULTIPLE_CHANGES",
		39: "PRIORITY_PLANNED_SUSPENDED",
		40: "PRIORITY_SUSPENDED",
	}
	MercuryEntitySelector_Priority_value = map[string]int32{
		"PRIORITY_NO_SCHEDULED_SERVICE":     1,
		"PRIORITY_NO_MIDDAY_SERVICE":        2,
		"PRIORITY_NO_OVERNIGHT_SERVICE":     3,
		"PRIORITY_NO_WEEKEND_SERVICE":       4,
		"PRIORITY_WEEKDAY_SCHEDULE":         5,
		"PRIORITY_WEEKEND_SCHEDULE":         6,
		"PRIORITY_SATURDAY_SCHEDULE":        7,
		"PRIORITY_SUNDAY_SCHEDULE":          8,
		"PRIORITY_EXTRA_SERVICE":            9,
		"PRIORITY_SPECIAL_SCHEDULE":         10,
		"PRIORITY_STATION_NOTICE":           11,
		"PRIORITY_SPECIAL_EVENT":            12,
		"PRIORITY_PLANNED_BOARDING_CHANGE":  13,
		"PRIORITY_BOARDING_CHANGE":          14,
		"PRIORITY_REDUCED_SERVICE":          15,
		"PRIORITY_PLANNED_WORK":             16,
		"PRIORITY_PLANNED_STATIONS_SKIPPED": 17,
		"PRIORITY_PLANNED_EXPRESS_TO_LOCAL": 18,
		"PRIORITY_SLOW_SPEEDS":              19,
		"PRIORITY_EXPECT_DELAYS":            20,
		"PRIORITY_PLANNED_LOCAL_TO_EXPRESS": 21,
		"PRIORITY_PLANNED_BUSES_DETOURED":   22,
		"PRIORITY_PLANNED_TRAINS_REROUTED":  23,
		"PRIORITY_PLANNED_SUBSTITUTE_BUSES": 24,
		"PRIORITY_PLANNED_PART_SUSPENDED":   25,
		"PRIORITY_PLANNED_MULTIPLE_CHANGES": 26,
		"PRIORITY_SOME_DELAYS":              27,
		"PRIORITY_STATIONS_SKIPPED":         28,
		"PRIORITY_EXPRESS_TO_LOCAL":         29,
		"PRIORITY_DELAYS":                   30,
		"PRIORITY_SOME_REROUTES":            31,
		"PRIORITY_LOCAL_TO_EXPRESS":         32,
		"PRIORITY_BUSES_DETOURED":           33,
		"PRIORITY_SERVICE_CHANGE":           34,
		"PRIORITY_TRAINS_REROUTED":          35,
		"PRIORITY_SUBSTITUTE_BUSES":         36,
		"PRIORITY_PART_SUSPENDED":           37,
		"PRIORITY_MULTIPLE_CHANGES":         38,
		"PRIORITY_PLANNED_SUSPENDED":        39,
		"PRIORITY_SUSPENDED":                40,
	}
)

func (x MercuryEntitySelector_Priority) Enum() *MercuryEntitySelector_Priority {
	p := new(MercuryEntitySelector_Priority)
	*p = x
	return p
}

func (x MercuryEntitySelector_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MercuryEntitySelector_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_us_ny_mta_alerts_extension_proto_enumTypes[0].Descriptor()
}

func (MercuryEntitySelector_Priority) Type() protoreflect.EnumType {
	return &file_proto_us_ny_mta_alerts_extension_proto_enumTypes[0]
}

func (x MercuryEntitySelector_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MercuryEntitySelector_Priority) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MercuryEntitySelector_Priority(num)
	return nil
}

// Deprecated: Use MercuryEntitySelector_Priority.Descriptor instead.
func (MercuryEntitySelector_Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_us_ny_mta_alerts_extension_proto_rawDescGZIP(), []int{3, 0}
}

// Mercury extensions for the Feed Header
type MercuryFeedHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version of the Mercury extensions
	// The current version is 1.0
	MercuryVersion *string `protobuf:"bytes,1,req,name=mercury_version,json=mercuryVersion" json:"mercury_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MercuryFeedHeader) Reset() {
	*x = MercuryFeedHeader{}
	mi := &file_proto_us_ny_mta_alerts_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MercuryFeedHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MercuryFeedHeader) ProtoMessage() {}

func (x *MercuryFeedHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_us_ny_mta_alerts_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MercuryFeedHeader.ProtoReflect.Descriptor instead.
func (*MercuryFeedHeader) Descriptor() ([]byte, []int) {
	return file_proto_us_ny_mta_alerts_extension_proto_rawDescGZIP(), []int{0}
}

func (x *MercuryFeedHeader) GetMercuryVersion() string {
	if x != nil && x.MercuryVersion != nil {
		return *x.MercuryVersion
	}
	return ""
}

type MercuryStationAlternative struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AffectedEntity *EntitySelector        `protobuf:"bytes,1,req,name=affected_entity,json=affectedEntity" json:"affected_entity,omitempty"`
	Notes          *TranslatedString      `protobuf:"bytes,2,req,name=notes" json:"notes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MercuryStationAlternative) Reset() {
	*x = MercuryStationAlternative{}
	mi := &file_proto_us_ny_mta_alerts_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MercuryStationAlternative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MercuryStationAlternative) ProtoMessage() {}

func (x *MercuryStationAlternative) ProtoReflect() protoreflect.Message {
	mi := &file_proto_us_ny_mta_alerts_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MercuryStationAlternative.ProtoReflect.Descriptor instead.
func (*MercuryStationAlternative) Descriptor() ([]byte, []int) {
	return file_proto_us_ny_mta_alerts_extension_proto_rawDescGZIP(), []int{1}
}

func (x *MercuryStationAlternative) GetAffectedEntity() *EntitySelector {
	if x != nil {
		return x.AffectedEntity
	}
	return nil
}

func (x *MercuryStationAlternative) GetNotes() *TranslatedString {
	if x != nil {
		return x.Notes
	}
	return nil
}

// Mercury extensions for the Feed Alert
type MercuryAlert struct {
	state              protoimpl.MessageState       `protogen:"open.v1"`
	CreatedAt          *uint64                      `protobuf:"varint,1,req,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt          *uint64                      `protobuf:"varint,2,req,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	AlertType          *string                      `protobuf:"bytes,3,req,name=alert_type,json=alertType" json:"alert_type,omitempty"`
	StationAlternative []*MercuryStationAlternative `protobuf:"bytes,4,rep,name=station_alternative,json=stationAlternative" json:"station_alternative,omitempty"`
	ServicePlanNumber  []string                     `protobuf:"bytes,5,rep,name=service_plan_number,json=servicePlanNumber" json:"service_plan_number,omitempty"`
	GeneralOrderNumber []string                     `protobuf:"bytes,6,rep,name=general_order_number,json=generalOrderNumber" json:"general_order_number,omitempty"`
	// A time interval, in seconds, indicating how long before each active period
	// consumers should display this alert. A value of 3600 here, for example,
	// suggests that this alert should be displayed 1 hour before each active
	// period. Consumers may choose to ignore this recommendation and display (or
	// not display) alerts based on their own logic if they so choose.
	DisplayBeforeActive *uint64 `protobuf:"varint,7,opt,name=display_before_active,json=displayBeforeActive" json:"display_before_active,omitempty"`
	// A human-friendly string that summarizes all active periods for this Alert,
	// i.e. "Sundays in May from 10:45pm to midnight"
	HumanReadableActivePeriod *TranslatedString `protobuf:"bytes,8,opt,name=human_readable_active_period,json=humanReadableActivePeriod" json:"human_readable_active_period,omitempty"`
	Directionality            *uint64           `protobuf:"varint,9,opt,name=directionality" json:"directionality,omitempty"`
	AffectedStations          []*EntitySelector `protobuf:"bytes,10,rep,name=affected_stations,json=affectedStations" json:"affected_stations,omitempty"`
	ScreensSummary            *TranslatedString `protobuf:"bytes,11,opt,name=screens_summary,json=screensSummary" json:"screens_summary,omitempty"`
	NoAffectedStations        *bool             `protobuf:"varint,12,opt,name=no_affected_stations,json=noAffectedStations" json:"no_affected_stations,omitempty"`
	// The ids of the planned work cloned from
	CloneId       *string `protobuf:"bytes,13,opt,name=clone_id,json=cloneId" json:"clone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MercuryAlert) Reset() {
	*x = MercuryAlert{}
	mi := &file_proto_us_ny_mta_alerts_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MercuryAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MercuryAlert) ProtoMessage() {}

func (x *MercuryAlert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_us_ny_mta_alerts_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MercuryAlert.ProtoReflect.Descriptor instead.
func (*MercuryAlert) Descriptor() ([]byte, []int) {
	return file_proto_us_ny_mta_alerts_extension_proto_rawDescGZIP(), []int{2}
}

func (x *MercuryAlert) GetCreatedAt() uint64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *MercuryAlert) GetUpdatedAt() uint64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *MercuryAlert) GetAlertType() string {
	if x != nil && x.AlertType != nil {
		return *x.AlertType
	}
	return ""
}

func (x *MercuryAlert) GetStationAlternative() []*MercuryStationAlternative {
	if x != nil {
		return x.StationAlternative
	}
	return nil
}

func (x *MercuryAlert) GetServicePlanNumber() []string {
	if x != nil {
		return x.ServicePlanNumber
	}
	return nil
}

func (x *MercuryAlert) GetGeneralOrderNumber() []string {
	if x != nil {
		return x.GeneralOrderNumber
	}
	return nil
}

func (x *MercuryAlert) GetDisplayBeforeActive() uint64 {
	if x != nil && x.DisplayBeforeActive != nil {
		return *x.DisplayBeforeActive
	}
	return 0
}

func (x *MercuryAlert) GetHumanReadableActivePeriod() *TranslatedString {
	if x != nil {
		return x.HumanReadableActivePeriod
	}
	return nil
}

func (x *MercuryAlert) GetDirectionality() uint64 {
	if x != nil && x.Directionality != nil {
		return *x.Directionality
	}
	return 0
}

func (x *MercuryAlert) GetAffectedStations() []*EntitySelector {
	if x != nil {
		return x.AffectedStations
	}
	return nil
}

func (x *MercuryAlert) GetScreensSummary() *TranslatedString {
	if x != nil {
		return x.ScreensSummary
	}
	return nil
}

func (x *MercuryAlert) GetNoAffectedStations() bool {
	if x != nil && x.NoAffectedStations != nil {
		return *x.NoAffectedStations
	}
	return false
}

func (x *MercuryAlert) GetCloneId() string {
	if x != nil && x.CloneId != nil {
		return *x.CloneId
	}
	return ""
}

// Mercury extensions for the Feed Entity Selector
type MercuryEntitySelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format for sort_order is 'GTFS-ID:Priority', e.g. 'MTASBWY:G:16'
	SortOrder     *string `protobuf:"bytes,1,req,name=sort_order,json=sortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MercuryEntitySelector) Reset() {
	*x = MercuryEntitySelector{}
	mi := &file_proto_us_ny_mta_alerts_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MercuryEntitySelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MercuryEntitySelector) ProtoMessage() {}

func (x *MercuryEntitySelector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_us_ny_mta_alerts_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MercuryEntitySelector.ProtoReflect.Descriptor instead.
func (*MercuryEntitySelector) Descriptor() ([]byte, []int) {
	return file_proto_us_ny_mta_alerts_extension_proto_rawDescGZIP(), []int{3}
}

func (x *MercuryEntitySelector) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

var file_proto_us_ny_mta_alerts_extension_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*Alert)(nil),
		ExtensionType: (*MercuryAlert)(nil),
		Field:         1001,
		Name:          "transit_rt.mercury_alert",
		Tag:           "bytes,1001,opt,name=mercury_alert",
		Filename:      "proto/us-ny-mta-alerts-extension.proto",
	},
	{
		ExtendedType:  (*EntitySelector)(nil),
		ExtensionType: (*MercuryEntitySelector)(nil),
		Field:         1001,
		Name:          "transit_rt.mercury_entity_selector",
		Tag:           "bytes,1001,opt,name=mercury_entity_selector",
		Filename:      "proto/us-ny-mta-alerts-extension.proto",
	},
}

// Extension fields to Alert.
var (
	// optional transit_rt.MercuryAlert mercury_alert = 1001;
	E_MercuryAlert = &file_proto_us_ny_mta_alerts_extension_proto_extTypes[0]
)

// Extension fields to EntitySelector.
var (
	// optional transit_rt.MercuryEntitySelector mercury_entity_selector = 1001;
	E_MercuryEntitySelector = &file_proto_us_ny_mta_alerts_extension_proto_extTypes[1]
)

var File_proto_us_ny_mta_alerts_extension_proto protoreflect.FileDescriptor

const file_proto_us_ny_mta_alerts_extension_proto_rawDesc = "" +
	"\n" +
	"&proto/us-ny-mta-alerts-extension.proto\x12\n" +
	"transit_rt\x1a\x19proto/gtfs-realtime.proto\"<\n" +
	"\x11MercuryFeedHeader\x12'\n" +
	"\x0fmercury_version\x18\x01 \x02(\tR\x0emercuryVersion\"\x94\x01\n" +
	"\x19MercuryStationAlternative\x12C\n" +
	"\x0faffected_entity\x18\x01 \x02(\v2\x1a.transit_rt.EntitySelectorR\x0eaffectedEntity\x122\n" +
	"\x05notes\x18\x02 \x02(\v2\x1c.transit_rt.TranslatedStringR\x05notes\"\xbd\x05\n" +
	"\fMercuryAlert\x12\x1d\n" +
	"\n" +
	"created_at\x18\x01 \x02(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x02(\x04R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x03 \x02(\tR\talertType\x12V\n" +
	"\x13station_alternative\x18\x04 \x03(\v2%.transit_rt.MercuryStationAlternativeR\x12stationAlternative\x12.\n" +
	"\x13service_plan_number\x18\x05 \x03(\tR\x11servicePlanNumber\x120\n" +
	"\x14general_order_number\x18\x06 \x03(\tR\x12generalOrderNumber\x122\n" +
	"\x15display_before_active\x18\a \x01(\x04R\x13displayBeforeActive\x12]\n" +
	"\x1chuman_readable_active_period\x18\b \x01(\v2\x1c.transit_rt.TranslatedStringR\x19humanReadableActivePeriod\x12&\n" +
	"\x0edirectionality\x18\t \x01(\x04R\x0edirectionality\x12G\n" +
	"\x11affected_stations\x18\n" +
	" \x03(\v2\x1a.transit_rt.EntitySelectorR\x10affectedStations\x12E\n" +
	"\x0fscreens_summary\x18\v \x01(\v2\x1c.transit_rt.TranslatedStringR\x0escreensSummary\x120\n" +
	"\x14no_affected_stations\x18\f \x01(\bR\x12noAffectedStations\x12\x19\n" +
	"\bclone_id\x18\r \x01(\tR\acloneId\"\xb3\n" +
	"\n" +
	"\x15MercuryEntitySelector\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x01 \x02(\tR\tsortOrder\"\xfa\t\n" +
	"\bPriority\x12!\n" +
	"\x1dPRIORITY_NO_SCHEDULED_SERVICE\x10\x01\x12\x1e\n" +
	"\x1aPRIORITY_NO_MIDDAY_SERVICE\x10\x02\x12!\n" +
	"\x1dPRIORITY_NO_OVERNIGHT_SERVICE\x10\x03\x12\x1f\n" +
	"\x1bPRIORITY_NO_WEEKEND_SERVICE\x10\x04\x12\x1d\n" +
	"\x19PRIORITY_WEEKDAY_SCHEDULE\x10\x05\x12\x1d\n" +
	"\x19PRIORITY_WEEKEND_SCHEDULE\x10\x06\x12\x1e\n" +
	"\x1aPRIORITY_SATURDAY_SCHEDULE\x10\a\x12\x1c\n" +
	"\x18PRIORITY_SUNDAY_SCHEDULE\x10\b\x12\x1a\n" +
	"\x16PRIORITY_EXTRA_SERVICE\x10\t\x12\x1d\n" +
	"\x19PRIORITY_SPECIAL_SCHEDULE\x10\n" +
	"\x12\x1b\n" +
	"\x17PRIORITY_STATION_NOTICE\x10\v\x12\x1a\n" +
	"\x16PRIORITY_SPECIAL_EVENT\x10\f\x12$\n" +
	" PRIORITY_PLANNED_BOARDING_CHANGE\x10\r\x12\x1c\n" +
	"\x18PRIORITY_BOARDING_CHANGE\x10\x0e\x12\x1c\n" +
	"\x18PRIORITY_REDUCED_SERVICE\x10\x0f\x12\x19\n" +
	"\x15PRIORITY_PLANNED_WORK\x10\x10\x12%\n" +
	"!PRIORITY_PLANNED_STATIONS_SKIPPED\x10\x11\x12%\n" +
	"!PRIORITY_PLANNED_EXPRESS_TO_LOCAL\x10\x12\x12\x18\n" +
	"\x14PRIORITY_SLOW_SPEEDS\x10\x13\x12\x1a\n" +
	"\x16PRIORITY_EXPECT_DELAYS\x10\x14\x12%\n" +
	"!PRIORITY_PLANNED_LOCAL_TO_EXPRESS\x10\x15\x12#\n" +
	"\x1fPRIORITY_PLANNED_BUSES_DETOURED\x10\x16\x12$\n" +
	" PRIORITY_PLANNED_TRAINS_REROUTED\x10\x17\x12%\n" +
	"!PRIORITY_PLANNED_SUBSTITUTE_BUSES\x10\x18\x12#\n" +
	"\x1fPRIORITY_PLANNED_PART_SUSPENDED\x10\x19\x12%\n" +
	"!PRIORITY_PLANNED_MULTIPLE_CHANGES\x10\x1a\x12\x18\n" +
	"\x14PRIORITY_SOME_DELAYS\x10\x1b\x12\x1d\n" +
	"\x19PRIORITY_STATIONS_SKIPPED\x10\x1c\x12\x1d\n" +
	"\x19PRIORITY_EXPRESS_TO_LOCAL\x10\x1d\x12\x13\n" +
	"\x0fPRIORITY_DELAYS\x10\x1e\x12\x1a\n" +
	"\x16PRIORITY_SOME_REROUTES\x10\x1f\x12\x1d\n" +
	"\x19PRIORITY_LOCAL_TO_EXPRESS\x10 \x12\x1b\n" +
	"\x17PRIORITY_BUSES_DETOURED\x10!\x12\x1b\n" +
	"\x17PRIORITY_SERVICE_CHANGE\x10\"\x12\x1c\n" +
	"\x18PRIORITY_TRAINS_REROUTED\x10#\x12\x1d\n" +
	"\x19PRIORITY_SUBSTITUTE_BUSES\x10$\x12\x1b\n" +
	"\x17PRIORITY_PART_SUSPENDED\x10%\x12\x1d\n" +
	"\x19PRIORITY_MULTIPLE_CHANGES\x10&\x12\x1e\n" +
	"\x1aPRIORITY_PLANNED_SUSPENDED\x10'\x12\x16\n" +
	"\x12PRIORITY_SUSPENDED\x10(:Q\n" +
	"\rmercury_alert\x12\x11.transit_rt.Alert\x18\xe9\a \x01(\v2\x18.transit_rt.MercuryAlertR\fmercuryAlert:v\n" +
	"\x17mercury_entity_selector\x12\x1a.transit_rt.EntitySelector\x18\xe9\a \x01(\v2!.transit_rt.MercuryEntitySelectorR\x15mercuryEntitySelectorBB\n" +
	"\x1bcom.google.transit.realtimeZ#github.com/jamespfennell/gtfs/proto"

var (
	file_proto_us_ny_mta_alerts_extension_proto_rawDescOnce sync.Once
	file_proto_us_ny_mta_alerts_extension_proto_rawDescData []byte
)

func file_proto_us_ny_mta_alerts_extension_proto_rawDescGZIP() []byte {
	file_proto_us_ny_mta_alerts_extension_proto_rawDescOnce.Do(func() {
		file_proto_us_ny_mta_alerts_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_us_ny_mta_alerts_extension_proto_rawDesc), len(file_proto_us_ny_mta_alerts_extension_proto_rawDesc)))
	})
	return file_proto_us_ny_mta_alerts_extension_proto_rawDescData
}

var file_proto_us_ny_mta_alerts_extension_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_us_ny_mta_alerts_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_us_ny_mta_alerts_extension_proto_goTypes = []any{
	(MercuryEntitySelector_Priority)(0), // 0: transit_rt.MercuryEntitySelector.Priority
	(*MercuryFeedHeader)(nil),           // 1: transit_rt.MercuryFeedHeader
	(*MercuryStationAlternative)(nil),   // 2: transit_rt.MercuryStationAlternative
	(*MercuryAlert)(nil),                // 3: transit_rt.MercuryAlert
	(*MercuryEntitySelector)(nil),       // 4: transit_rt.MercuryEntitySelector
	(*EntitySelector)(nil),              // 5: transit_rt.EntitySelector
	(*TranslatedString)(nil),            // 6: transit_rt.TranslatedString
	(*Alert)(nil),                       // 7: transit_rt.Alert
}
var file_proto_us_ny_mta_alerts_extension_proto_depIdxs = []int32{
	5,  // 0: transit_rt.MercuryStationAlternative.affected_entity:type_name -> transit_rt.EntitySelector
	6,  // 1: transit_rt.MercuryStationAlternative.notes:type_name -> transit_rt.TranslatedString
	2,  // 2: transit_rt.MercuryAlert.station_alternative:type_name -> transit_rt.MercuryStationAlternative
	6,  // 3: transit_rt.MercuryAlert.human_readable_active_period:type_name -> transit_rt.TranslatedString
	5,  // 4: transit_rt.MercuryAlert.affected_stations:type_name -> transit_rt.EntitySelector
	6,  // 5: transit_rt.MercuryAlert.screens_summary:type_name -> transit_rt.TranslatedString
	7,  // 6: transit_rt.mercury_alert:extendee -> transit_rt.Alert
	5,  // 7: transit_rt.mercury_entity_selector:extendee -> transit_rt.EntitySelector
	3,  // 8: transit_rt.mercury_alert:type_name -> transit_rt.MercuryAlert
	4,  // 9: transit_rt.mercury_entity_selector:type_name -> transit_rt.MercuryEntitySelector
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	8,  // [8:10] is the sub-list for extension type_name
	6,  // [6:8] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_us_ny_mta_alerts_extension_proto_init() }
func file_proto_us_ny_mta_alerts_extension_proto_init() {
	if File_proto_us_ny_mta_alerts_extension_proto != nil {
		return
	}
	file_proto_gtfs_realtime_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_us_ny_mta_alerts_extension_proto_rawDesc), len(file_proto_us_ny_mta_alerts_extension_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_us_ny_mta_alerts_extension_proto_goTypes,
		DependencyIndexes: file_proto_us_ny_mta_alerts_extension_proto_depIdxs,
		EnumInfos:         file_proto_us_ny_mta_alerts_extension_proto_enumTypes,
		MessageInfos:      file_proto_us_ny_mta_alerts_extension_proto_msgTypes,
		ExtensionInfos:    file_proto_us_ny_mta_alerts_extension_proto_extTypes,
	}.Build()
	File_proto_us_ny_mta_alerts_extension_proto = out.File
	file_proto_us_ny_mta_alerts_extension_proto_goTypes = nil
	file_proto_us_ny_mta_alerts_extension_proto_depIdxs = nil
}
